<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>scl2</string>
		<string>SCL2</string>
	</array>
	<key>name</key>
	<string>Siemens Structured Control Language (SCL)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=:)([A-Za-z]\w*)(?=(:=|;))</string>
			<key>name</key>
			<string>support.class.scl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(ARRAY|BOOL|BYTE|CHAR|COUNTER|DATE|DATE_AND_TIME|END_REGION|INT|DINT|DT|DWORD|POINTER|REAL|S5TIME|STRING|STRUCT|TIME|TIMER|TIME_OF_DAY|TOD|WORD|PRESET_TIMER|REGION)\b</string>
			<key>name</key>
			<string>support.class.scl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\;</string>
			<key>name</key>
			<string>punctuation.terminator.statement.scl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.scl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment.block.scl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.scl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.scl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.scl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\btrue\b</string>
			<key>name</key>
			<string>constant.language.boolean.true.scl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\bfalse\b</string>
			<key>name</key>
			<string>constant.language.boolean.false.scl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(break|case|end_case|continue|do|else|elsif|for|end_for|goto|if|end_if|return|of|while|end_while|then)\b</string>
			<key>name</key>
			<string>keyword.control.scl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(var_input|var_output|var|var_temp|end_var)\b</string>
			<key>name</key>
			<string>keyword.control.scl</string>
		</dict>		
		<dict>
			<key>match</key>
			<string>(?i)\b(not|mod|div|and|or|xor)\b</string>
			<key>name</key>
			<string>keyword.operator.scl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!|\$|&amp;|&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;|!|&amp;&amp;|\*|/|\-|\+|:|:=|=|\b(void)\b</string>
			<key>name</key>
			<string>keyword.operator.scl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.scl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.scl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.scl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.scl</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.scl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(FUNCTION_BLOCK)\s+([a-zA-Z_$]\w*)?</string>
			<key>name</key>
			<string>storage.type.function.scl</string>
		</dict>
		<dict>			
			<key>match</key>
			<string>(?i)\b(END_FUNCTION_BLOCK)\b</string>
			<key>name</key>
			<string>storage.type.function.scl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.scl</string>
				</dict>				
			</dict>
			<key>match</key>
			<string>\b([a-zA-Z_$]\w*)?(?=(\s*(\()(.*?)(\))))</string>
			<key>name</key>
			<string>support.function.scl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=(\.|,|\())([a-zA-Z_$]\w*)?(?=:=)</string>
			<key>name</key>
			<string>support.constant.scl</string>
		</dict>
	</array>	
	<key>scopeName</key>
	<string>source.scl</string>
	<key>uuid</key>
	<string>1986D1CA-8D49-11E1-9C73-D083BAE59B18</string>
</dict>
</plist>
